import { createOperationDispatcher } from '../../shared/nodes/createNodeDispatcher';

import {
	descriptionGetAccount,
	descriptionGetConsentCampaign,
	descriptionGetConsentDecision,
	descriptionGetIdentityGroup,
	descriptionGetIdentityUser,
	descriptionGetOvhAccount,
	descriptionGetOvhAccountMovement,
	descriptionGetSshKey,
	descriptionGetSubAccount,
	descriptionGetUserToken,
	descriptionListGroupUsers,
	descriptionListOvhAccountMovements,
	descriptionListUserTokens,
	executeGetAccount,
	executeGetAutorenew,
	executeGetConsentCampaign,
	executeGetConsentDecision,
	executeGetIdentityGroup,
	executeGetIdentityProvider,
	executeGetIdentityUser,
	executeGetOvhAccount,
	executeGetOvhAccountMovement,
	executeGetSshKey,
	executeGetSubAccount,
	executeGetUserToken,
	executeListAvailablePaymentMeans,
	executeListConsentCampaigns,
	executeListGroupUsers,
	executeListIdentityGroups,
	executeListIdentityUsers,
	executeListOvhAccountMovements,
	executeListOvhAccounts,
	executeListSshKeys,
	executeListSubAccounts,
	executeListUserTokens,
} from './operations/account.operation';
import {
	descriptionGetApiApplication,
	descriptionGetApiCredential,
	descriptionGetApiLogKind,
	descriptionGetApiLogSelf,
	descriptionGetApiLogServices,
	descriptionGetApiLogSubscription,
	descriptionGetAuditLogKind,
	descriptionGetAuditLogSubscription,
	descriptionGetCredentialApplication,
	descriptionGetOAuth2Client,
	executeGetApiApplication,
	executeGetApiCredential,
	executeGetApiLogKind,
	executeGetApiLogSelf,
	executeGetApiLogServices,
	executeGetApiLogSubscription,
	executeGetAuditLogKind,
	executeGetAuditLogSubscription,
	executeGetAuditLogs,
	executeGetCredentialApplication,
	executeGetOAuth2Client,
	executeListApiApplications,
	executeListApiCredentials,
	executeListApiLogKinds,
	executeListApiLogSubscriptions,
	executeListApiLogsSelf,
	executeListApiLogsServices,
	executeListAuditLogKinds,
	executeListAuditLogSubscriptions,
	executeListOAuth2Clients,
} from './operations/api.operation';
import {
	descriptionGetBill,
	descriptionGetBillDebt,
	descriptionGetBillDebtOperation,
	descriptionGetBillDebtOperationAssociatedObject,
	descriptionGetBillDetail,
	descriptionGetBillPayment,
	descriptionGetBillingGroup,
	descriptionGetBillingGroupService,
	descriptionGetConsumptionReport,
	descriptionGetPurchaseOrder,
	descriptionListBillDebtOperations,
	descriptionListBillDetails,
	descriptionListBillingGroupServices,
	descriptionListBills,
	executeGetBill,
	executeGetBillDebt,
	executeGetBillDebtOperation,
	executeGetBillDebtOperationAssociatedObject,
	executeGetBillDetail,
	executeGetBillPayment,
	executeGetBillingGroup,
	executeGetBillingGroupService,
	executeGetConsumptionReport,
	executeGetPurchaseOrder,
	executeListBillDebtOperations,
	executeListBillDetails,
	executeListBillingGroupServices,
	executeListBillingGroups,
	executeListBills,
	executeListConsumptionReports,
	executeListPurchaseOrders,
} from './operations/billing.operation';
import {
	descriptionGetContact,
	descriptionGetContactFields,
	descriptionGetDocument,
	descriptionGetTag,
	executeGetContact,
	executeGetContactFields,
	executeGetDocument,
	executeGetTag,
	executeListAvailableTags,
	executeListContacts,
	executeListDocuments,
	executeListTags,
} from './operations/contact.operation';
import {
	descriptionGetContactChangeTask,
	descriptionGetDnsTask,
	descriptionGetDomainTask,
	descriptionGetDomainTaskArgument,
	descriptionGetDomainTaskProgress,
	descriptionGetEmailChangeTask,
	descriptionGetSubscription,
	descriptionListDomainTaskArguments,
	executeGetContactChangeTask,
	executeGetDnsTask,
	executeGetDomainTask,
	executeGetDomainTaskArgument,
	executeGetDomainTaskProgress,
	executeGetEmailChangeTask,
	executeGetSubscription,
	executeListContactChangeTasks,
	executeListDnsTasks,
	executeListDomainTaskArguments,
	executeListDomainTasks,
	executeListEmailChangeTasks,
	executeListSubscriptions,
} from './operations/domain.operation';
import {
	descriptionGetCorrectiveInvoice,
	descriptionGetCorrectiveInvoiceDebt,
	descriptionGetCorrectiveInvoiceDebtOperation,
	descriptionGetCorrectiveInvoiceDebtOperationAssociatedObject,
	descriptionGetCorrectiveInvoiceDetail,
	descriptionGetCorrectiveInvoicePayment,
	descriptionGetCreditBalance,
	descriptionGetCreditBalanceMovement,
	descriptionGetDebtAccountDebt,
	descriptionGetDebtAccountDebtOperation,
	descriptionGetDebtAccountDebtOperationAssociatedObject,
	descriptionGetDeposit,
	descriptionGetDepositDetail,
	descriptionGetDepositPaidBill,
	descriptionGetDepositPayment,
	descriptionGetRefund,
	descriptionGetRefundDetail,
	descriptionGetRefundPayment,
	descriptionGetReverseBill,
	descriptionGetReverseBillDetail,
	descriptionGetReverseBillPayment,
	descriptionGetWithdrawal,
	descriptionGetWithdrawalDetail,
	descriptionGetWithdrawalPayment,
	descriptionListCorrectiveInvoiceDebtOperations,
	descriptionListCorrectiveInvoiceDetails,
	descriptionListCorrectiveInvoices,
	descriptionListCreditBalanceMovements,
	descriptionListDebtAccountDebtOperations,
	descriptionListDepositDetails,
	descriptionListDepositPaidBills,
	descriptionListDeposits,
	descriptionListRefundDetails,
	descriptionListRefunds,
	descriptionListReverseBillDetails,
	descriptionListReverseBills,
	descriptionListWithdrawalDetails,
	descriptionListWithdrawals,
	executeGetCorrectiveInvoice,
	executeGetCorrectiveInvoiceDebt,
	executeGetCorrectiveInvoiceDebtOperation,
	executeGetCorrectiveInvoiceDebtOperationAssociatedObject,
	executeGetCorrectiveInvoiceDetail,
	executeGetCorrectiveInvoicePayment,
	executeGetCreditBalance,
	executeGetCreditBalanceMovement,
	executeGetDebtAccount,
	executeGetDebtAccountDebt,
	executeGetDebtAccountDebtOperation,
	executeGetDebtAccountDebtOperationAssociatedObject,
	executeGetDeposit,
	executeGetDepositDetail,
	executeGetDepositPaidBill,
	executeGetDepositPayment,
	executeGetRefund,
	executeGetRefundDetail,
	executeGetRefundPayment,
	executeGetReverseBill,
	executeGetReverseBillDetail,
	executeGetReverseBillPayment,
	executeGetWithdrawal,
	executeGetWithdrawalDetail,
	executeGetWithdrawalPayment,
	executeListCorrectiveInvoiceDebtOperations,
	executeListCorrectiveInvoiceDetails,
	executeListCorrectiveInvoices,
	executeListCreditBalanceMovements,
	executeListCreditBalances,
	executeListDebtAccountDebtOperations,
	executeListDebtAccountDebts,
	executeListDepositDetails,
	executeListDepositPaidBills,
	executeListDeposits,
	executeListRefundDetails,
	executeListRefunds,
	executeListReverseBillDetails,
	executeListReverseBills,
	executeListWithdrawalDetails,
	executeListWithdrawals,
} from './operations/financial.operation';
import {
	descriptionGetEmail,
	descriptionGetFidelityMovement,
	descriptionGetIpOrganisation,
	descriptionGetMigration,
	descriptionGetMigrationAgreement,
	descriptionGetMigrationContract,
	descriptionListMigrationContracts,
	executeGetConsumptionHistory,
	executeGetCurrentConsumption,
	executeGetEmail,
	executeGetFidelityAccount,
	executeGetFidelityMovement,
	executeGetForecastConsumption,
	executeGetIpOrganisation,
	executeGetMarketing,
	executeGetMigration,
	executeGetMigrationAgreement,
	executeGetMigrationContract,
	executeListAvailableMailingLists,
	executeListEmailHistory,
	executeListFidelityMovements,
	executeListIpOrganisations,
	executeListMigrationContracts,
	executeListMigrations,
} from './operations/notification.operation';
import {
	descriptionGetAbuse,
	descriptionGetAccessRestrictionIp,
	descriptionGetAccessRestrictionSms,
	descriptionGetAccessRestrictionTotp,
	descriptionGetAccessRestrictionU2f,
	descriptionGetAgreement,
	descriptionGetAgreementContract,
	descriptionGetCarbonCalculatorTask,
	descriptionGetSla,
	descriptionGetSlaCanBeApplied,
	descriptionGetSlaStatus,
	descriptionListSlaServices,
	executeGetAbuse,
	executeGetAccessRestrictionBackupCode,
	executeGetAccessRestrictionDeveloperMode,
	executeGetAccessRestrictionIp,
	executeGetAccessRestrictionIpDefaultRule,
	executeGetAccessRestrictionSms,
	executeGetAccessRestrictionTotp,
	executeGetAccessRestrictionU2f,
	executeGetAgreement,
	executeGetAgreementContract,
	executeGetBringYourOwnIpToken,
	executeGetCarbonCalculatorHasInvoice,
	executeGetCarbonCalculatorTask,
	executeGetInsight,
	executeGetPartnerLevel,
	executeGetRecommendations,
	executeGetSla,
	executeGetSlaCanBeApplied,
	executeGetSlaStatus,
	executeGetSupportLevel,
	executeGetVipStatus,
	executeListAbuse,
	executeListAccessRestrictionIps,
	executeListAccessRestrictionSms,
	executeListAccessRestrictionTotp,
	executeListAccessRestrictionU2f,
	executeListAgreements,
	executeListCarbonCalculatorTasks,
	executeListCertificates,
	executeListSlaServices,
	executeListSlas,
} from './operations/partner.operation';
import {
	descriptionGetBankAccount,
	descriptionGetCreditCard,
	descriptionGetDeferredPaymentAccount,
	descriptionGetOrder,
	descriptionGetOrderAssociatedObject,
	descriptionGetOrderBalance,
	descriptionGetOrderConsumptionDetails,
	descriptionGetOrderDebt,
	descriptionGetOrderDebtOperation,
	descriptionGetOrderDebtOperationAssociatedObject,
	descriptionGetOrderDetail,
	descriptionGetOrderDetailExtension,
	descriptionGetOrderFollowUp,
	descriptionGetOrderPayment,
	descriptionGetOrderPaymentMeans,
	descriptionGetOrderStatus,
	descriptionGetPaymentMethod,
	descriptionGetPaymentTransaction,
	descriptionGetPaypalAccount,
	descriptionListBankAccounts,
	descriptionListOrderAvailablePaymentMeans,
	descriptionListOrderBalances,
	descriptionListOrderDebtOperations,
	descriptionListOrderDetails,
	descriptionListOrderPaymentMethods,
	descriptionListOrders,
	executeGetBankAccount,
	executeGetCreditCard,
	executeGetDeferredPaymentAccount,
	executeGetOrder,
	executeGetOrderAssociatedObject,
	executeGetOrderBalance,
	executeGetOrderConsumptionDetails,
	executeGetOrderDebt,
	executeGetOrderDebtOperation,
	executeGetOrderDebtOperationAssociatedObject,
	executeGetOrderDetail,
	executeGetOrderDetailExtension,
	executeGetOrderFollowUp,
	executeGetOrderPayment,
	executeGetOrderPaymentMeans,
	executeGetOrderStatus,
	executeGetPaymentMethod,
	executeGetPaymentTransaction,
	executeGetPaypalAccount,
	executeListBankAccounts,
	executeListCreditCards,
	executeListDeferredPaymentAccounts,
	executeListOrderAvailablePaymentMeans,
	executeListOrderBalances,
	executeListOrderDebtOperations,
	executeListOrderDetails,
	executeListOrderPaymentMethods,
	executeListOrders,
	executeListPaymentAvailableMethods,
	executeListPaymentMethods,
	executeListPaymentTransactions,
	executeListPaypalAccounts,
} from './operations/payment.operation';
import {
	descriptionGetFaxCustomDomain,
	descriptionGetTelephonyDefaultIpRestriction,
	executeGetFaxCustomDomain,
	executeGetTelephonyDefaultIpRestriction,
	executeGetTelephonySettings,
	executeGetXdslSettings,
	executeListFaxCustomDomains,
	executeListTelephonyDefaultIpRestrictions,
} from './operations/telecom.operation';

const noProps = (): never[] => [];

const { description, execute } = createOperationDispatcher(
	'meOperation',
	'me',
	[
	{
		name: 'Get Abuse',
		value: 'getAbuse',
		action: 'Get an abuse case',
		execute: executeGetAbuse,
		description: descriptionGetAbuse,
	},
	{
		name: 'Get Access Restriction Backup Code',
		value: 'getAccessRestrictionBackupCode',
		action: 'Get access restriction backup code',
		execute: executeGetAccessRestrictionBackupCode,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Access Restriction Developer Mode',
		value: 'getAccessRestrictionDeveloperMode',
		action: 'Get access restriction developer mode',
		execute: executeGetAccessRestrictionDeveloperMode,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Access Restriction IP',
		value: 'getAccessRestrictionIp',
		action: 'Get an IP restriction',
		execute: executeGetAccessRestrictionIp,
		description: descriptionGetAccessRestrictionIp,
	},
	{
		name: 'Get Access Restriction IP Default Rule',
		value: 'getAccessRestrictionIpDefaultRule',
		action: 'Get access restriction IP default rule',
		execute: executeGetAccessRestrictionIpDefaultRule,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Access Restriction SMS',
		value: 'getAccessRestrictionSms',
		action: 'Get an SMS account',
		execute: executeGetAccessRestrictionSms,
		description: descriptionGetAccessRestrictionSms,
	},
	{
		name: 'Get Access Restriction TOTP',
		value: 'getAccessRestrictionTotp',
		action: 'Get a TOTP account',
		execute: executeGetAccessRestrictionTotp,
		description: descriptionGetAccessRestrictionTotp,
	},
	{
		name: 'Get Access Restriction U2F',
		value: 'getAccessRestrictionU2f',
		action: 'Get a U2F account',
		execute: executeGetAccessRestrictionU2f,
		description: descriptionGetAccessRestrictionU2f,
	},
	{
		name: 'Get Account',
		value: 'getAccount',
		action: 'Get your nichandle details',
		execute: executeGetAccount,
		description: descriptionGetAccount,
		show: false,
		default: true,
	},
	{
		name: 'Get Agreement',
		value: 'getAgreement',
		action: 'Get an agreement',
		execute: executeGetAgreement,
		description: descriptionGetAgreement,
	},
	{
		name: 'Get Agreement Contract',
		value: 'getAgreementContract',
		action: 'Get an agreement contract',
		execute: executeGetAgreementContract,
		description: descriptionGetAgreementContract,
	},
	{
		name: 'Get API Application',
		value: 'getApiApplication',
		action: 'Get API application',
		execute: executeGetApiApplication,
		description: descriptionGetApiApplication,
	},
	{
		name: 'Get API Credential',
		value: 'getApiCredential',
		action: 'Get API credential',
		execute: executeGetApiCredential,
		description: descriptionGetApiCredential,
	},
	{
		name: 'Get API Log (Self)',
		value: 'getApiLogSelf',
		action: 'Get an API call log',
		execute: executeGetApiLogSelf,
		description: descriptionGetApiLogSelf,
	},
	{
		name: 'Get API Log (Services)',
		value: 'getApiLogServices',
		action: 'Get a service API log',
		execute: executeGetApiLogServices,
		description: descriptionGetApiLogServices,
	},
	{
		name: 'Get API Log Kind',
		value: 'getApiLogKind',
		action: 'Get API log kind',
		execute: executeGetApiLogKind,
		description: descriptionGetApiLogKind,
	},
	{
		name: 'Get API Log Subscription',
		value: 'getApiLogSubscription',
		action: 'Get API log subscription',
		execute: executeGetApiLogSubscription,
		description: descriptionGetApiLogSubscription,
	},
	{
		name: 'Get Audit Log Kind',
		value: 'getAuditLogKind',
		action: 'Get an audit log kind',
		execute: executeGetAuditLogKind,
		description: descriptionGetAuditLogKind,
	},
	{
		name: 'Get Audit Log Subscription',
		value: 'getAuditLogSubscription',
		action: 'Get an audit subscription',
		execute: executeGetAuditLogSubscription,
		description: descriptionGetAuditLogSubscription,
	},
	{
		name: 'Get Audit Logs',
		value: 'getAuditLogs',
		action: 'Get audit logs',
		execute: executeGetAuditLogs,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Autorenew',
		value: 'getAutorenew',
		action: 'Get autorenew settings',
		execute: executeGetAutorenew,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Bank Account',
		value: 'getBankAccount',
		action: 'Get a bank account',
		execute: executeGetBankAccount,
		description: descriptionGetBankAccount,
	},
	{
		name: 'Get Bill',
		value: 'getBill',
		action: 'Get bill details',
		execute: executeGetBill,
		description: descriptionGetBill,
	},
	{
		name: 'Get Bill Debt',
		value: 'getBillDebt',
		action: 'Get bill debt',
		execute: executeGetBillDebt,
		description: descriptionGetBillDebt,
	},
	{
		name: 'Get Bill Debt Operation',
		value: 'getBillDebtOperation',
		action: 'Get a debt operation',
		execute: executeGetBillDebtOperation,
		description: descriptionGetBillDebtOperation,
	},
	{
		name: 'Get Bill Debt Operation Associated Object',
		value: 'getBillDebtOperationAssociatedObject',
		action: 'Get debt operation associated object',
		execute: executeGetBillDebtOperationAssociatedObject,
		description: descriptionGetBillDebtOperationAssociatedObject,
	},
	{
		name: 'Get Bill Detail',
		value: 'getBillDetail',
		action: 'Get a bill detail',
		execute: executeGetBillDetail,
		description: descriptionGetBillDetail,
	},
	{
		name: 'Get Bill Payment',
		value: 'getBillPayment',
		action: 'Get bill payment',
		execute: executeGetBillPayment,
		description: descriptionGetBillPayment,
	},
	{
		name: 'Get Billing Group',
		value: 'getBillingGroup',
		action: 'Get a billing group',
		execute: executeGetBillingGroup,
		description: descriptionGetBillingGroup,
	},
	{
		name: 'Get Billing Group Service',
		value: 'getBillingGroupService',
		action: 'Get a billing group service',
		execute: executeGetBillingGroupService,
		description: descriptionGetBillingGroupService,
	},
	{
		name: 'Get Bring Your Own IP Token',
		value: 'getBringYourOwnIpToken',
		action: 'Get BYO IP token',
		execute: executeGetBringYourOwnIpToken,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Carbon Calculator Has Invoice',
		value: 'getCarbonCalculatorHasInvoice',
		action: 'Check carbon calculator invoice data',
		execute: executeGetCarbonCalculatorHasInvoice,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Carbon Calculator Task',
		value: 'getCarbonCalculatorTask',
		action: 'Get a carbon calculator task',
		execute: executeGetCarbonCalculatorTask,
		description: descriptionGetCarbonCalculatorTask,
	},
	{
		name: 'Get Consent Campaign',
		value: 'getConsentCampaign',
		action: 'Get a consent campaign',
		execute: executeGetConsentCampaign,
		description: descriptionGetConsentCampaign,
	},
	{
		name: 'Get Consent Decision',
		value: 'getConsentDecision',
		action: 'Get consent decision',
		execute: executeGetConsentDecision,
		description: descriptionGetConsentDecision,
	},
	{
		name: 'Get Consumption History',
		value: 'getConsumptionHistory',
		action: 'Get consumption history',
		execute: executeGetConsumptionHistory,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Consumption Report',
		value: 'getConsumptionReport',
		action: 'Get a consumption report',
		execute: executeGetConsumptionReport,
		description: descriptionGetConsumptionReport,
	},
	{
		name: 'Get Contact',
		value: 'getContact',
		action: 'Get a contact',
		execute: executeGetContact,
		description: descriptionGetContact,
	},
	{
		name: 'Get Contact Change Task',
		value: 'getContactChangeTask',
		action: 'Get a contact change task',
		execute: executeGetContactChangeTask,
		description: descriptionGetContactChangeTask,
	},
	{
		name: 'Get Contact Fields',
		value: 'getContactFields',
		action: 'Get contact fields info',
		execute: executeGetContactFields,
		description: descriptionGetContactFields,
	},
	{
		name: 'Get Corrective Invoice',
		value: 'getCorrectiveInvoice',
		action: 'Get a corrective invoice',
		execute: executeGetCorrectiveInvoice,
		description: descriptionGetCorrectiveInvoice,
	},
	{
		name: 'Get Corrective Invoice Debt',
		value: 'getCorrectiveInvoiceDebt',
		action: 'Get corrective invoice debt',
		execute: executeGetCorrectiveInvoiceDebt,
		description: descriptionGetCorrectiveInvoiceDebt,
	},
	{
		name: 'Get Corrective Invoice Debt Operation',
		value: 'getCorrectiveInvoiceDebtOperation',
		action: 'Get a corrective invoice debt operation',
		execute: executeGetCorrectiveInvoiceDebtOperation,
		description: descriptionGetCorrectiveInvoiceDebtOperation,
	},
	{
		name: 'Get Corrective Invoice Debt Operation Object',
		value: 'getCorrectiveInvoiceDebtOperationAssociatedObject',
		action: 'Get associated object of debt operation',
		execute: executeGetCorrectiveInvoiceDebtOperationAssociatedObject,
		description: descriptionGetCorrectiveInvoiceDebtOperationAssociatedObject,
	},
	{
		name: 'Get Corrective Invoice Detail',
		value: 'getCorrectiveInvoiceDetail',
		action: 'Get a corrective invoice detail',
		execute: executeGetCorrectiveInvoiceDetail,
		description: descriptionGetCorrectiveInvoiceDetail,
	},
	{
		name: 'Get Corrective Invoice Payment',
		value: 'getCorrectiveInvoicePayment',
		action: 'Get a corrective invoice payment',
		execute: executeGetCorrectiveInvoicePayment,
		description: descriptionGetCorrectiveInvoicePayment,
	},
	{
		name: 'Get Credential Application',
		value: 'getCredentialApplication',
		action: 'Get credential application',
		execute: executeGetCredentialApplication,
		description: descriptionGetCredentialApplication,
	},
	{
		name: 'Get Credit Balance',
		value: 'getCreditBalance',
		action: 'Get a credit balance',
		execute: executeGetCreditBalance,
		description: descriptionGetCreditBalance,
	},
	{
		name: 'Get Credit Balance Movement',
		value: 'getCreditBalanceMovement',
		action: 'Get a credit balance movement',
		execute: executeGetCreditBalanceMovement,
		description: descriptionGetCreditBalanceMovement,
	},
	{
		name: 'Get Credit Card',
		value: 'getCreditCard',
		action: 'Get a credit card',
		execute: executeGetCreditCard,
		description: descriptionGetCreditCard,
	},
	{
		name: 'Get Current Consumption',
		value: 'getCurrentConsumption',
		action: 'Get current consumptions',
		execute: executeGetCurrentConsumption,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Debt Account',
		value: 'getDebtAccount',
		action: 'Get the debt account',
		execute: executeGetDebtAccount,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Debt Account Debt',
		value: 'getDebtAccountDebt',
		action: 'Get a debt account debt',
		execute: executeGetDebtAccountDebt,
		description: descriptionGetDebtAccountDebt,
	},
	{
		name: 'Get Debt Account Debt Operation',
		value: 'getDebtAccountDebtOperation',
		action: 'Get a debt account debt operation',
		execute: executeGetDebtAccountDebtOperation,
		description: descriptionGetDebtAccountDebtOperation,
	},
	{
		name: 'Get Debt Account Debt Operation Object',
		value: 'getDebtAccountDebtOperationAssociatedObject',
		action: 'Get associated object of debt operation',
		execute: executeGetDebtAccountDebtOperationAssociatedObject,
		description: descriptionGetDebtAccountDebtOperationAssociatedObject,
	},
	{
		name: 'Get Deferred Payment Account',
		value: 'getDeferredPaymentAccount',
		action: 'Get a deferred payment account',
		execute: executeGetDeferredPaymentAccount,
		description: descriptionGetDeferredPaymentAccount,
	},
	{
		name: 'Get Deposit',
		value: 'getDeposit',
		action: 'Get a deposit',
		execute: executeGetDeposit,
		description: descriptionGetDeposit,
	},
	{
		name: 'Get Deposit Detail',
		value: 'getDepositDetail',
		action: 'Get a deposit detail',
		execute: executeGetDepositDetail,
		description: descriptionGetDepositDetail,
	},
	{
		name: 'Get Deposit Paid Bill',
		value: 'getDepositPaidBill',
		action: 'Get a deposit paid bill',
		execute: executeGetDepositPaidBill,
		description: descriptionGetDepositPaidBill,
	},
	{
		name: 'Get Deposit Payment',
		value: 'getDepositPayment',
		action: 'Get a deposit payment',
		execute: executeGetDepositPayment,
		description: descriptionGetDepositPayment,
	},
	{
		name: 'Get DNS Task',
		value: 'getDnsTask',
		action: 'Get a DNS task',
		execute: executeGetDnsTask,
		description: descriptionGetDnsTask,
	},
	{
		name: 'Get Document',
		value: 'getDocument',
		action: 'Get a document',
		execute: executeGetDocument,
		description: descriptionGetDocument,
	},
	{
		name: 'Get Domain Task',
		value: 'getDomainTask',
		action: 'Get a domain task',
		execute: executeGetDomainTask,
		description: descriptionGetDomainTask,
	},
	{
		name: 'Get Domain Task Argument',
		value: 'getDomainTaskArgument',
		action: 'Get a domain task argument',
		execute: executeGetDomainTaskArgument,
		description: descriptionGetDomainTaskArgument,
	},
	{
		name: 'Get Domain Task Progress',
		value: 'getDomainTaskProgress',
		action: 'Get a domain task progress',
		execute: executeGetDomainTaskProgress,
		description: descriptionGetDomainTaskProgress,
	},
	{
		name: 'Get Email',
		value: 'getEmail',
		action: 'Get an email',
		execute: executeGetEmail,
		description: descriptionGetEmail,
	},
	{
		name: 'Get Email Change Task',
		value: 'getEmailChangeTask',
		action: 'Get an email change task',
		execute: executeGetEmailChangeTask,
		description: descriptionGetEmailChangeTask,
	},
	{
		name: 'Get Fax Custom Domain',
		value: 'getFaxCustomDomain',
		action: 'Get a fax custom domain',
		execute: executeGetFaxCustomDomain,
		description: descriptionGetFaxCustomDomain,
	},
	{
		name: 'Get Fidelity Account',
		value: 'getFidelityAccount',
		action: 'Get fidelity account',
		execute: executeGetFidelityAccount,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Fidelity Movement',
		value: 'getFidelityMovement',
		action: 'Get a fidelity movement',
		execute: executeGetFidelityMovement,
		description: descriptionGetFidelityMovement,
	},
	{
		name: 'Get Forecast Consumption',
		value: 'getForecastConsumption',
		action: 'Get forecasted consumptions',
		execute: executeGetForecastConsumption,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Identity Group',
		value: 'getIdentityGroup',
		action: 'Get an IAM group',
		execute: executeGetIdentityGroup,
		description: descriptionGetIdentityGroup,
	},
	{
		name: 'Get Identity Provider',
		value: 'getIdentityProvider',
		action: 'Get identity provider',
		execute: executeGetIdentityProvider,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Identity User',
		value: 'getIdentityUser',
		action: 'Get an IAM user',
		execute: executeGetIdentityUser,
		description: descriptionGetIdentityUser,
	},
	{
		name: 'Get Insight',
		value: 'getInsight',
		action: 'Get insight access token',
		execute: executeGetInsight,
		description: noProps,
		show: false,
	},
	{
		name: 'Get IP Organisation',
		value: 'getIpOrganisation',
		action: 'Get an IP organisation',
		execute: executeGetIpOrganisation,
		description: descriptionGetIpOrganisation,
	},
	{
		name: 'Get Marketing',
		value: 'getMarketing',
		action: 'Get marketing consent',
		execute: executeGetMarketing,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Migration',
		value: 'getMigration',
		action: 'Get a migration',
		execute: executeGetMigration,
		description: descriptionGetMigration,
	},
	{
		name: 'Get Migration Agreement',
		value: 'getMigrationAgreement',
		action: 'Get a migration agreement',
		execute: executeGetMigrationAgreement,
		description: descriptionGetMigrationAgreement,
	},
	{
		name: 'Get Migration Contract',
		value: 'getMigrationContract',
		action: 'Get a migration contract',
		execute: executeGetMigrationContract,
		description: descriptionGetMigrationContract,
	},
	{
		name: 'Get OAuth2 Client',
		value: 'getOAuth2Client',
		action: 'Get an OAuth2 client',
		execute: executeGetOAuth2Client,
		description: descriptionGetOAuth2Client,
	},
	{
		name: 'Get Order',
		value: 'getOrder',
		action: 'Get an order',
		execute: executeGetOrder,
		description: descriptionGetOrder,
	},
	{
		name: 'Get Order Associated Object',
		value: 'getOrderAssociatedObject',
		action: 'Get order associated object',
		execute: executeGetOrderAssociatedObject,
		description: descriptionGetOrderAssociatedObject,
	},
	{
		name: 'Get Order Consumption Details',
		value: 'getOrderConsumptionDetails',
		action: 'Get order consumption details',
		execute: executeGetOrderConsumptionDetails,
		description: descriptionGetOrderConsumptionDetails,
	},
	{
		name: 'Get Order Credit Balance',
		value: 'getOrderBalance',
		action: 'Get an order credit balance',
		execute: executeGetOrderBalance,
		description: descriptionGetOrderBalance,
	},
	{
		name: 'Get Order Debt',
		value: 'getOrderDebt',
		action: 'Get order debt',
		execute: executeGetOrderDebt,
		description: descriptionGetOrderDebt,
	},
	{
		name: 'Get Order Debt Operation',
		value: 'getOrderDebtOperation',
		action: 'Get an order debt operation',
		execute: executeGetOrderDebtOperation,
		description: descriptionGetOrderDebtOperation,
	},
	{
		name: 'Get Order Debt Operation Object',
		value: 'getOrderDebtOperationAssociatedObject',
		action: 'Get associated object of debt operation',
		execute: executeGetOrderDebtOperationAssociatedObject,
		description: descriptionGetOrderDebtOperationAssociatedObject,
	},
	{
		name: 'Get Order Detail',
		value: 'getOrderDetail',
		action: 'Get an order detail',
		execute: executeGetOrderDetail,
		description: descriptionGetOrderDetail,
	},
	{
		name: 'Get Order Detail Extension',
		value: 'getOrderDetailExtension',
		action: 'Get order detail extension',
		execute: executeGetOrderDetailExtension,
		description: descriptionGetOrderDetailExtension,
	},
	{
		name: 'Get Order Follow Up',
		value: 'getOrderFollowUp',
		action: 'Get order tracking',
		execute: executeGetOrderFollowUp,
		description: descriptionGetOrderFollowUp,
	},
	{
		name: 'Get Order Payment',
		value: 'getOrderPayment',
		action: 'Get order payment',
		execute: executeGetOrderPayment,
		description: descriptionGetOrderPayment,
	},
	{
		name: 'Get Order Payment Means',
		value: 'getOrderPaymentMeans',
		action: 'Get order payment means',
		execute: executeGetOrderPaymentMeans,
		description: descriptionGetOrderPaymentMeans,
	},
	{
		name: 'Get Order Status',
		value: 'getOrderStatus',
		action: 'Get order status',
		execute: executeGetOrderStatus,
		description: descriptionGetOrderStatus,
	},
	{
		name: 'Get OVH Account',
		value: 'getOvhAccount',
		action: 'Get an OVH account',
		execute: executeGetOvhAccount,
		description: descriptionGetOvhAccount,
	},
	{
		name: 'Get OVH Account Movement',
		value: 'getOvhAccountMovement',
		action: 'Get an account movement',
		execute: executeGetOvhAccountMovement,
		description: descriptionGetOvhAccountMovement,
	},
	{
		name: 'Get Partner Level',
		value: 'getPartnerLevel',
		action: 'Get partner level',
		execute: executeGetPartnerLevel,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Payment Method',
		value: 'getPaymentMethod',
		action: 'Get a payment method',
		execute: executeGetPaymentMethod,
		description: descriptionGetPaymentMethod,
	},
	{
		name: 'Get Payment Transaction',
		value: 'getPaymentTransaction',
		action: 'Get a transaction',
		execute: executeGetPaymentTransaction,
		description: descriptionGetPaymentTransaction,
	},
	{
		name: 'Get PayPal Account',
		value: 'getPaypalAccount',
		action: 'Get a PayPal account',
		execute: executeGetPaypalAccount,
		description: descriptionGetPaypalAccount,
	},
	{
		name: 'Get Purchase Order',
		value: 'getPurchaseOrder',
		action: 'Get a purchase order',
		execute: executeGetPurchaseOrder,
		description: descriptionGetPurchaseOrder,
	},
	{
		name: 'Get Recommendations',
		value: 'getRecommendations',
		action: 'Get recommendations',
		execute: executeGetRecommendations,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Refund',
		value: 'getRefund',
		action: 'Get a refund',
		execute: executeGetRefund,
		description: descriptionGetRefund,
	},
	{
		name: 'Get Refund Detail',
		value: 'getRefundDetail',
		action: 'Get a refund detail',
		execute: executeGetRefundDetail,
		description: descriptionGetRefundDetail,
	},
	{
		name: 'Get Refund Payment',
		value: 'getRefundPayment',
		action: 'Get a refund payment',
		execute: executeGetRefundPayment,
		description: descriptionGetRefundPayment,
	},
	{
		name: 'Get Reverse Bill',
		value: 'getReverseBill',
		action: 'Get a reverse bill',
		execute: executeGetReverseBill,
		description: descriptionGetReverseBill,
	},
	{
		name: 'Get Reverse Bill Detail',
		value: 'getReverseBillDetail',
		action: 'Get a reverse bill detail',
		execute: executeGetReverseBillDetail,
		description: descriptionGetReverseBillDetail,
	},
	{
		name: 'Get Reverse Bill Payment',
		value: 'getReverseBillPayment',
		action: 'Get a reverse bill payment',
		execute: executeGetReverseBillPayment,
		description: descriptionGetReverseBillPayment,
	},
	{
		name: 'Get SLA',
		value: 'getSla',
		action: 'Get an SLA',
		execute: executeGetSla,
		description: descriptionGetSla,
	},
	{
		name: 'Get SLA Can Be Applied',
		value: 'getSlaCanBeApplied',
		action: 'Check if SLA can be applied',
		execute: executeGetSlaCanBeApplied,
		description: descriptionGetSlaCanBeApplied,
	},
	{
		name: 'Get SLA Status',
		value: 'getSlaStatus',
		action: 'Get SLA status',
		execute: executeGetSlaStatus,
		description: descriptionGetSlaStatus,
	},
	{
		name: 'Get SSH Key',
		value: 'getSshKey',
		action: 'Get an SSH key',
		execute: executeGetSshKey,
		description: descriptionGetSshKey,
	},
	{
		name: 'Get Sub-Account',
		value: 'getSubAccount',
		action: 'Get a sub-account',
		execute: executeGetSubAccount,
		description: descriptionGetSubAccount,
	},
	{
		name: 'Get Subscription',
		value: 'getSubscription',
		action: 'Get a subscription type',
		execute: executeGetSubscription,
		description: descriptionGetSubscription,
	},
	{
		name: 'Get Support Level',
		value: 'getSupportLevel',
		action: 'Get support level',
		execute: executeGetSupportLevel,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Tag',
		value: 'getTag',
		action: 'Get a tag',
		execute: executeGetTag,
		description: descriptionGetTag,
	},
	{
		name: 'Get Telephony Default IP Restriction',
		value: 'getTelephonyDefaultIpRestriction',
		action: 'Get a SIP IP restriction',
		execute: executeGetTelephonyDefaultIpRestriction,
		description: descriptionGetTelephonyDefaultIpRestriction,
	},
	{
		name: 'Get Telephony Settings',
		value: 'getTelephonySettings',
		action: 'Get telephony settings',
		execute: executeGetTelephonySettings,
		description: noProps,
		show: false,
	},
	{
		name: 'Get User Token',
		value: 'getUserToken',
		action: 'Get a personal access token',
		execute: executeGetUserToken,
		description: descriptionGetUserToken,
	},
	{
		name: 'Get VIP Status',
		value: 'getVipStatus',
		action: 'Get VIP status',
		execute: executeGetVipStatus,
		description: noProps,
		show: false,
	},
	{
		name: 'Get Withdrawal',
		value: 'getWithdrawal',
		action: 'Get a withdrawal',
		execute: executeGetWithdrawal,
		description: descriptionGetWithdrawal,
	},
	{
		name: 'Get Withdrawal Detail',
		value: 'getWithdrawalDetail',
		action: 'Get a withdrawal detail',
		execute: executeGetWithdrawalDetail,
		description: descriptionGetWithdrawalDetail,
	},
	{
		name: 'Get Withdrawal Payment',
		value: 'getWithdrawalPayment',
		action: 'Get a withdrawal payment',
		execute: executeGetWithdrawalPayment,
		description: descriptionGetWithdrawalPayment,
	},
	{
		name: 'Get XDSL Settings',
		value: 'getXdslSettings',
		action: 'Get XDSL settings',
		execute: executeGetXdslSettings,
		description: noProps,
		show: false,
	},
	{
		name: 'List Abuse',
		value: 'listAbuse',
		action: 'List abuse cases',
		execute: executeListAbuse,
		description: noProps,
		show: false,
	},
	{
		name: 'List Access Restriction IPs',
		value: 'listAccessRestrictionIps',
		action: 'List IP restrictions',
		execute: executeListAccessRestrictionIps,
		description: noProps,
		show: false,
	},
	{
		name: 'List Access Restriction SMS',
		value: 'listAccessRestrictionSms',
		action: 'List SMS accounts',
		execute: executeListAccessRestrictionSms,
		description: noProps,
		show: false,
	},
	{
		name: 'List Access Restriction TOTP',
		value: 'listAccessRestrictionTotp',
		action: 'List TOTP accounts',
		execute: executeListAccessRestrictionTotp,
		description: noProps,
		show: false,
	},
	{
		name: 'List Access Restriction U2F',
		value: 'listAccessRestrictionU2f',
		action: 'List U2F accounts',
		execute: executeListAccessRestrictionU2f,
		description: noProps,
		show: false,
	},
	{
		name: 'List Agreements',
		value: 'listAgreements',
		action: 'List agreements',
		execute: executeListAgreements,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Applications',
		value: 'listApiApplications',
		action: 'List API applications',
		execute: executeListApiApplications,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Credentials',
		value: 'listApiCredentials',
		action: 'List API credentials',
		execute: executeListApiCredentials,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Log Kinds',
		value: 'listApiLogKinds',
		action: 'List API log kinds',
		execute: executeListApiLogKinds,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Log Subscriptions',
		value: 'listApiLogSubscriptions',
		action: 'List API log subscriptions',
		execute: executeListApiLogSubscriptions,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Logs (Self)',
		value: 'listApiLogsSelf',
		action: 'List your API calls',
		execute: executeListApiLogsSelf,
		description: noProps,
		show: false,
	},
	{
		name: 'List API Logs (Services)',
		value: 'listApiLogsServices',
		action: 'List API calls on services',
		execute: executeListApiLogsServices,
		description: noProps,
		show: false,
	},
	{
		name: 'List Audit Log Kinds',
		value: 'listAuditLogKinds',
		action: 'List audit log kinds',
		execute: executeListAuditLogKinds,
		description: noProps,
		show: false,
	},
	{
		name: 'List Audit Log Subscriptions',
		value: 'listAuditLogSubscriptions',
		action: 'List audit subscriptions',
		execute: executeListAuditLogSubscriptions,
		description: noProps,
		show: false,
	},
	{
		name: 'List Available Mailing Lists',
		value: 'listAvailableMailingLists',
		action: 'List available mailing lists',
		execute: executeListAvailableMailingLists,
		description: noProps,
		show: false,
	},
	{
		name: 'List Available Payment Means',
		value: 'listAvailablePaymentMeans',
		action: 'List available payment methods',
		execute: executeListAvailablePaymentMeans,
		description: noProps,
		show: false,
	},
	{
		name: 'List Available Payment Methods',
		value: 'listPaymentAvailableMethods',
		action: 'List available payment methods',
		execute: executeListPaymentAvailableMethods,
		description: noProps,
		show: false,
	},
	{
		name: 'List Available Tags',
		value: 'listAvailableTags',
		action: 'List available tags',
		execute: executeListAvailableTags,
		description: noProps,
		show: false,
	},
	{
		name: 'List Bank Accounts',
		value: 'listBankAccounts',
		action: 'List bank accounts',
		execute: executeListBankAccounts,
		description: descriptionListBankAccounts,
	},
	{
		name: 'List Bill Debt Operations',
		value: 'listBillDebtOperations',
		action: 'List bill debt operations',
		execute: executeListBillDebtOperations,
		description: descriptionListBillDebtOperations,
	},
	{
		name: 'List Bill Details',
		value: 'listBillDetails',
		action: 'List bill details',
		execute: executeListBillDetails,
		description: descriptionListBillDetails,
	},
	{
		name: 'List Billing Group Services',
		value: 'listBillingGroupServices',
		action: 'List billing group services',
		execute: executeListBillingGroupServices,
		description: descriptionListBillingGroupServices,
	},
	{
		name: 'List Billing Groups',
		value: 'listBillingGroups',
		action: 'List billing groups',
		execute: executeListBillingGroups,
		description: noProps,
		show: false,
	},
	{
		name: 'List Bills',
		value: 'listBills',
		action: 'List all bills',
		execute: executeListBills,
		description: descriptionListBills,
	},
	{
		name: 'List Carbon Calculator Tasks',
		value: 'listCarbonCalculatorTasks',
		action: 'List carbon calculator tasks',
		execute: executeListCarbonCalculatorTasks,
		description: noProps,
		show: false,
	},
	{
		name: 'List Certificates',
		value: 'listCertificates',
		action: 'List certificates',
		execute: executeListCertificates,
		description: noProps,
		show: false,
	},
	{
		name: 'List Consent Campaigns',
		value: 'listConsentCampaigns',
		action: 'List consent campaigns',
		execute: executeListConsentCampaigns,
		description: noProps,
		show: false,
	},
	{
		name: 'List Consumption Reports',
		value: 'listConsumptionReports',
		action: 'List consumption reports',
		execute: executeListConsumptionReports,
		description: noProps,
		show: false,
	},
	{
		name: 'List Contact Change Tasks',
		value: 'listContactChangeTasks',
		action: 'List contact change tasks',
		execute: executeListContactChangeTasks,
		description: noProps,
		show: false,
	},
	{
		name: 'List Contacts',
		value: 'listContacts',
		action: 'List contacts',
		execute: executeListContacts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Corrective Invoice Debt Operations',
		value: 'listCorrectiveInvoiceDebtOperations',
		action: 'List corrective invoice debt operations',
		execute: executeListCorrectiveInvoiceDebtOperations,
		description: descriptionListCorrectiveInvoiceDebtOperations,
	},
	{
		name: 'List Corrective Invoice Details',
		value: 'listCorrectiveInvoiceDetails',
		action: 'List corrective invoice details',
		execute: executeListCorrectiveInvoiceDetails,
		description: descriptionListCorrectiveInvoiceDetails,
	},
	{
		name: 'List Corrective Invoices',
		value: 'listCorrectiveInvoices',
		action: 'List corrective invoices',
		execute: executeListCorrectiveInvoices,
		description: descriptionListCorrectiveInvoices,
	},
	{
		name: 'List Credit Balance Movements',
		value: 'listCreditBalanceMovements',
		action: 'List credit balance movements',
		execute: executeListCreditBalanceMovements,
		description: descriptionListCreditBalanceMovements,
	},
	{
		name: 'List Credit Balances',
		value: 'listCreditBalances',
		action: 'List credit balances',
		execute: executeListCreditBalances,
		description: noProps,
		show: false,
	},
	{
		name: 'List Credit Cards',
		value: 'listCreditCards',
		action: 'List credit cards',
		execute: executeListCreditCards,
		description: noProps,
		show: false,
	},
	{
		name: 'List Debt Account Debt Operations',
		value: 'listDebtAccountDebtOperations',
		action: 'List debt account debt operations',
		execute: executeListDebtAccountDebtOperations,
		description: descriptionListDebtAccountDebtOperations,
	},
	{
		name: 'List Debt Account Debts',
		value: 'listDebtAccountDebts',
		action: 'List debt account debts',
		execute: executeListDebtAccountDebts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Deferred Payment Accounts',
		value: 'listDeferredPaymentAccounts',
		action: 'List deferred payment accounts',
		execute: executeListDeferredPaymentAccounts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Deposit Details',
		value: 'listDepositDetails',
		action: 'List deposit details',
		execute: executeListDepositDetails,
		description: descriptionListDepositDetails,
	},
	{
		name: 'List Deposit Paid Bills',
		value: 'listDepositPaidBills',
		action: 'List deposit paid bills',
		execute: executeListDepositPaidBills,
		description: descriptionListDepositPaidBills,
	},
	{
		name: 'List Deposits',
		value: 'listDeposits',
		action: 'List deposits',
		execute: executeListDeposits,
		description: descriptionListDeposits,
	},
	{
		name: 'List DNS Tasks',
		value: 'listDnsTasks',
		action: 'List DNS tasks',
		execute: executeListDnsTasks,
		description: noProps,
		show: false,
	},
	{
		name: 'List Documents',
		value: 'listDocuments',
		action: 'List documents',
		execute: executeListDocuments,
		description: noProps,
		show: false,
	},
	{
		name: 'List Domain Task Arguments',
		value: 'listDomainTaskArguments',
		action: 'List domain task arguments',
		execute: executeListDomainTaskArguments,
		description: descriptionListDomainTaskArguments,
	},
	{
		name: 'List Domain Tasks',
		value: 'listDomainTasks',
		action: 'List domain tasks',
		execute: executeListDomainTasks,
		description: noProps,
		show: false,
	},
	{
		name: 'List Email Change Tasks',
		value: 'listEmailChangeTasks',
		action: 'List email change tasks',
		execute: executeListEmailChangeTasks,
		description: noProps,
		show: false,
	},
	{
		name: 'List Email History',
		value: 'listEmailHistory',
		action: 'List email history',
		execute: executeListEmailHistory,
		description: noProps,
		show: false,
	},
	{
		name: 'List Fax Custom Domains',
		value: 'listFaxCustomDomains',
		action: 'List fax custom domains',
		execute: executeListFaxCustomDomains,
		description: noProps,
		show: false,
	},
	{
		name: 'List Fidelity Movements',
		value: 'listFidelityMovements',
		action: 'List fidelity movements',
		execute: executeListFidelityMovements,
		description: noProps,
		show: false,
	},
	{
		name: 'List Group Users',
		value: 'listGroupUsers',
		action: 'List group members',
		execute: executeListGroupUsers,
		description: descriptionListGroupUsers,
	},
	{
		name: 'List Identity Groups',
		value: 'listIdentityGroups',
		action: 'List IAM groups',
		execute: executeListIdentityGroups,
		description: noProps,
		show: false,
	},
	{
		name: 'List Identity Users',
		value: 'listIdentityUsers',
		action: 'List IAM users',
		execute: executeListIdentityUsers,
		description: noProps,
		show: false,
	},
	{
		name: 'List IP Organisations',
		value: 'listIpOrganisations',
		action: 'List IP organisations',
		execute: executeListIpOrganisations,
		description: noProps,
		show: false,
	},
	{
		name: 'List Migration Contracts',
		value: 'listMigrationContracts',
		action: 'List migration contracts',
		execute: executeListMigrationContracts,
		description: descriptionListMigrationContracts,
	},
	{
		name: 'List Migrations',
		value: 'listMigrations',
		action: 'List migrations',
		execute: executeListMigrations,
		description: noProps,
		show: false,
	},
	{
		name: 'List OAuth2 Clients',
		value: 'listOAuth2Clients',
		action: 'List OAuth2 clients',
		execute: executeListOAuth2Clients,
		description: noProps,
		show: false,
	},
	{
		name: 'List Order Available Payment Means',
		value: 'listOrderAvailablePaymentMeans',
		action: 'List available payment means for order',
		execute: executeListOrderAvailablePaymentMeans,
		description: descriptionListOrderAvailablePaymentMeans,
	},
	{
		name: 'List Order Credit Balances',
		value: 'listOrderBalances',
		action: 'List credit balances for order',
		execute: executeListOrderBalances,
		description: descriptionListOrderBalances,
	},
	{
		name: 'List Order Debt Operations',
		value: 'listOrderDebtOperations',
		action: 'List order debt operations',
		execute: executeListOrderDebtOperations,
		description: descriptionListOrderDebtOperations,
	},
	{
		name: 'List Order Details',
		value: 'listOrderDetails',
		action: 'List order details',
		execute: executeListOrderDetails,
		description: descriptionListOrderDetails,
	},
	{
		name: 'List Order Payment Methods',
		value: 'listOrderPaymentMethods',
		action: 'List payment methods for order',
		execute: executeListOrderPaymentMethods,
		description: descriptionListOrderPaymentMethods,
	},
	{
		name: 'List Orders',
		value: 'listOrders',
		action: 'List all orders',
		execute: executeListOrders,
		description: descriptionListOrders,
	},
	{
		name: 'List OVH Account Movements',
		value: 'listOvhAccountMovements',
		action: 'List account movements',
		execute: executeListOvhAccountMovements,
		description: descriptionListOvhAccountMovements,
	},
	{
		name: 'List OVH Accounts',
		value: 'listOvhAccounts',
		action: 'List all OVH accounts',
		execute: executeListOvhAccounts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Payment Methods',
		value: 'listPaymentMethods',
		action: 'List payment methods',
		execute: executeListPaymentMethods,
		description: noProps,
		show: false,
	},
	{
		name: 'List Payment Transactions',
		value: 'listPaymentTransactions',
		action: 'List payment transactions',
		execute: executeListPaymentTransactions,
		description: noProps,
		show: false,
	},
	{
		name: 'List PayPal Accounts',
		value: 'listPaypalAccounts',
		action: 'List PayPal accounts',
		execute: executeListPaypalAccounts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Purchase Orders',
		value: 'listPurchaseOrders',
		action: 'List purchase orders',
		execute: executeListPurchaseOrders,
		description: noProps,
		show: false,
	},
	{
		name: 'List Refund Details',
		value: 'listRefundDetails',
		action: 'List refund details',
		execute: executeListRefundDetails,
		description: descriptionListRefundDetails,
	},
	{
		name: 'List Refunds',
		value: 'listRefunds',
		action: 'List refunds',
		execute: executeListRefunds,
		description: descriptionListRefunds,
	},
	{
		name: 'List Reverse Bill Details',
		value: 'listReverseBillDetails',
		action: 'List reverse bill details',
		execute: executeListReverseBillDetails,
		description: descriptionListReverseBillDetails,
	},
	{
		name: 'List Reverse Bills',
		value: 'listReverseBills',
		action: 'List reverse bills',
		execute: executeListReverseBills,
		description: descriptionListReverseBills,
	},
	{
		name: 'List SLA Services',
		value: 'listSlaServices',
		action: 'List SLA services',
		execute: executeListSlaServices,
		description: descriptionListSlaServices,
	},
	{
		name: 'List SLAs',
		value: 'listSlas',
		action: 'List active SLAs',
		execute: executeListSlas,
		description: noProps,
		show: false,
	},
	{
		name: 'List SSH Keys',
		value: 'listSshKeys',
		action: 'List SSH keys',
		execute: executeListSshKeys,
		description: noProps,
		show: false,
	},
	{
		name: 'List Sub-Accounts',
		value: 'listSubAccounts',
		action: 'List sub-accounts',
		execute: executeListSubAccounts,
		description: noProps,
		show: false,
	},
	{
		name: 'List Subscriptions',
		value: 'listSubscriptions',
		action: 'List available subscriptions',
		execute: executeListSubscriptions,
		description: noProps,
		show: false,
	},
	{
		name: 'List Tags',
		value: 'listTags',
		action: 'List tags',
		execute: executeListTags,
		description: noProps,
		show: false,
	},
	{
		name: 'List Telephony Default IP Restrictions',
		value: 'listTelephonyDefaultIpRestrictions',
		action: 'List default SIP IP restrictions',
		execute: executeListTelephonyDefaultIpRestrictions,
		description: noProps,
		show: false,
	},
	{
		name: 'List User Tokens',
		value: 'listUserTokens',
		action: 'List personal access tokens',
		execute: executeListUserTokens,
		description: descriptionListUserTokens,
	},
	{
		name: 'List Withdrawal Details',
		value: 'listWithdrawalDetails',
		action: 'List withdrawal details',
		execute: executeListWithdrawalDetails,
		description: descriptionListWithdrawalDetails,
	},
	{
		name: 'List Withdrawals',
		value: 'listWithdrawals',
		action: 'List withdrawals',
		execute: executeListWithdrawals,
		description: descriptionListWithdrawals,
	},
	],
);

export { description, execute };
