/* eslint-disable n8n-nodes-base/node-filename-against-convention, n8n-nodes-base/node-param-default-missing, n8n-nodes-base/node-param-display-name-not-first-position */
import type {
	IDataObject,
	IExecuteFunctions,
	IDisplayOptions,
	INodeExecutionData,
	INodeProperties,
} from 'n8n-workflow';
import { getClient } from '../../../shared/transport/ApiClient';
import type { FilterDefinition } from '../../../shared/nodes/filterOptions';
import { filtersCollection } from '../../../shared/nodes/filterOptions';
import { buildFilterQuery } from '../../../shared/nodes/filterQuery';

/* ------------------------------------------------------------------ */
/*  Ticket filter definitions                                         */
/* ------------------------------------------------------------------ */

export const TICKET_FILTERS: FilterDefinition[] = [
	// ── Date Range ────────────────────────────────────────────────────
	{
		group: 'dateRange',
		groupDisplayName: 'Date Range',
		name: 'minCreationDate',
		displayName: 'Created After',
		queryParam: 'minCreationDate',
		type: 'dateTime',
		description: 'Minimum creation date (ISO 8601)',
	},
	{
		group: 'dateRange',
		groupDisplayName: 'Date Range',
		name: 'maxCreationDate',
		displayName: 'Created Before',
		queryParam: 'maxCreationDate',
		type: 'dateTime',
		description: 'Maximum creation date (ISO 8601)',
	},

	// ── Status ────────────────────────────────────────────────────────
	{
		group: 'status',
		groupDisplayName: 'Status',
		name: 'value',
		displayName: 'Status',
		queryParam: 'status',
		type: 'options',
		description: 'Status of the ticket',
		options: [
			{ name: 'Closed', value: 'closed' },
			{ name: 'Open', value: 'open' },
			{ name: 'Unknown', value: 'unknown' },
		],
	},

	// ── Category & Product ────────────────────────────────────────────
	{
		group: 'category',
		groupDisplayName: 'Category & Product',
		name: 'category',
		displayName: 'Category',
		queryParam: 'category',
		type: 'options',
		options: [
			{ name: 'Assistance', value: 'assistance' },
			{ name: 'Billing', value: 'billing' },
			{ name: 'Incident', value: 'incident' },
		],
	},
	{
		group: 'category',
		groupDisplayName: 'Category & Product',
		name: 'product',
		displayName: 'Product',
		queryParam: 'product',
		type: 'options',
		options: [
			{ name: 'ADSL', value: 'adsl' },
			{ name: 'CDN', value: 'cdn' },
			{ name: 'Dedicated', value: 'dedicated' },
			{ name: 'Dedicated Billing', value: 'dedicated-billing' },
			{ name: 'Dedicated Other', value: 'dedicated-other' },
			{ name: 'Dedicated Cloud', value: 'dedicatedcloud' },
			{ name: 'Domain', value: 'domain' },
			{ name: 'Exchange', value: 'exchange' },
			{ name: 'Fax', value: 'fax' },
			{ name: 'Hosting', value: 'hosting' },
			{ name: 'Housing', value: 'housing' },
			{ name: 'IaaS', value: 'iaas' },
			{ name: 'Mail', value: 'mail' },
			{ name: 'Network', value: 'network' },
			{ name: 'Public Cloud', value: 'publiccloud' },
			{ name: 'SMS', value: 'sms' },
			{ name: 'SSL', value: 'ssl' },
			{ name: 'Storage', value: 'storage' },
			{ name: 'Telecom Billing', value: 'telecom-billing' },
			{ name: 'Telecom Other', value: 'telecom-other' },
			{ name: 'VAC', value: 'vac' },
			{ name: 'VoIP', value: 'voip' },
			{ name: 'VPS', value: 'vps' },
			{ name: 'Web Billing', value: 'web-billing' },
			{ name: 'Web Other', value: 'web-other' },
		],
	},

	// ── Search ────────────────────────────────────────────────────────
	{
		group: 'search',
		groupDisplayName: 'Search',
		name: 'subject',
		displayName: 'Subject',
		queryParam: 'subject',
		type: 'string',
	},
	{
		group: 'search',
		groupDisplayName: 'Search',
		name: 'ticketNumber',
		displayName: 'Ticket Number',
		queryParam: 'ticketNumber',
		type: 'string',
	},
	{
		group: 'search',
		groupDisplayName: 'Search',
		name: 'serviceName',
		displayName: 'Service Name',
		queryParam: 'serviceName',
		type: 'string',
	},

	// ── Flags ─────────────────────────────────────────────────────────
	{
		group: 'flags',
		groupDisplayName: 'Flags',
		name: 'archived',
		displayName: 'Archived',
		queryParam: 'archived',
		type: 'options',
		options: [
			{ name: 'Yes', value: true },
			{ name: 'No', value: false },
		],
	},
	{
		group: 'flags',
		groupDisplayName: 'Flags',
		name: 'customerReplyNeeded',
		displayName: 'Customer Reply Needed',
		queryParam: 'customerReplyNeeded',
		type: 'options',
		options: [
			{ name: 'Yes', value: true },
			{ name: 'No', value: false },
		],
	},
	{
		group: 'flags',
		groupDisplayName: 'Flags',
		name: 'excludeAutogenerated',
		displayName: 'Exclude Auto-generated',
		queryParam: 'excludeAutogenerated',
		type: 'options',
		options: [
			{ name: 'Yes', value: true },
			{ name: 'No', value: false },
		],
	},

	// ── Pagination ────────────────────────────────────────────────────
	{
		group: 'pagination',
		groupDisplayName: 'Pagination',
		name: 'pageSize',
		displayName: 'Page Size',
		queryParam: 'pageSize',
		type: 'number',
		default: 0,
		description: 'Number of tickets to fetch (enables page-based fetching)',
	},
	{
		group: 'pagination',
		groupDisplayName: 'Pagination',
		name: 'page',
		displayName: 'Page',
		queryParam: 'page',
		type: 'number',
		default: 0,
		description: 'Page to fetch (only valid when Page Size is set)',
	},
];

/* ------------------------------------------------------------------ */
/*  Description                                                       */
/* ------------------------------------------------------------------ */

export function description(displayOptions: IDisplayOptions): INodeProperties[] {
	return filtersCollection(displayOptions, TICKET_FILTERS);
}

/* ------------------------------------------------------------------ */
/*  Execute                                                           */
/* ------------------------------------------------------------------ */

export async function execute(
	this: IExecuteFunctions,
	itemIndex?: number,
): Promise<INodeExecutionData[]> {
	const client = getClient(this);
	const qs = buildFilterQuery(this, itemIndex ?? 0, TICKET_FILTERS);
	const data = (await client.httpGet('/support/tickets', qs)) as IDataObject[];
	return this.helpers.returnJsonArray(data);
}
